name: Test and Lint

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# Add concurrency control
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    strategy:
      matrix:
        python-version: [3.10, 3.11, 3.12, 3.13]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    
    # Add dependency cache
    - name: Cache dependencies
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ matrix.python-version }}-${{ hashFiles('**/requirements*.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-${{ matrix.python-version }}-
          ${{ runner.os }}-pip-

    - name: Install dependencies
      env:
        PYTHONUNBUFFERED: 1
        PYTHONDONTWRITEBYTECODE: 1
      run: |
        python -m pip install --upgrade pip
        pip install -e ".[test]"
    
    - name: Lint with ruff
      env:
        PYTHONUNBUFFERED: 1
      run: |
        ruff check .
    
    - name: Type check with mypy
      env:
        PYTHONUNBUFFERED: 1
      run: |
        mypy src
    
    - name: Test with pytest
      env:
        PYTHONUNBUFFERED: 1
      run: |
        pytest
